### ISSUE TITLE
Trouble generating and saving a docx with next.js and fileSaver.js

### ISSUE THREAD

**Issue by MemduhG** [TurboDocx/html-to-docx#43]
I'm using this library in a next.js server action to generate a fileBuffer. A client component loads the buffer into a Blob and saves it. Microsoft Word can't open the resulting docx file. Is there something I'm missing here with regards to correctly using this?

Here is the part of the server action that generates the buffer:
```js
    const htmlString = `<!DOCTYPE html>
                    <html lang="en">
                        <head>
                            <meta charset="UTF-8" />
                            <title>Document</title>
                        </head>
                        <body>
                            <p>Here is a sample string</p>
                        </body>
                    </html>`;

    const fileBuffer = await HTMLtoDOCX(htmlString, null, {
        table: { row: { cantSplit: true } },
        footer: true,
        pageNumber: true,
      });
    return fileBuffer;
```

Here is how I get the buffer and save it on the client side:

```js
  async function handleWord() {
    const fileBuffer = await getDocx(petitionProps)
    
    saveAs(new Blob([fileBuffer],  
                 {type: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'}), 
                 'html-to-docx.docx');
  }
```

Opening the file I download produces this error in Microsoft Word:

> Word found unreadable content in html-to-docx.docx. Do you want to recover the contents of this document? If you trust the source of this document, click Yes.

I am using version 0.3.1 of this library.

**Comment by nicolasiscoding** [comment]
Hi @MemduhG , there's a couple things to unpack here. Can you post the output of the file? Also, if you can, after letting Microsoft Word recover the file, can you post that here as well? I will likely run this through [OOXML Tools](https://chromewebstore.google.com/detail/ooxml-tools/bjmmjfdegplhkefakjkccocjanekbapn) to check the diff (and keep in mind that the recovery handles certain tags differently than us but could provide some hints) 

The below is the example we run in our example's folder as part of regression testing. We use a much bigger `htmlString` then the example you provided. Can you go into the example folder, paste your example string and run the code? This will hint to us if it's an issue with the converter,  the save library you may be using, or something further. 

```
const fileBuffer = await HTMLtoDOCX(htmlString, null, {
        table: { row: { cantSplit: true } },
        footer: true,
        pageNumber: true,
    });

    fs.writeFile(filePath, fileBuffer, (error) => {
        if (error) {
            console.log('Docx file creation failed');
            return;
        }
        console.log('Docx file created successfully');
    });
 ```

**Comment by MemduhG** [comment]
Since I'm using next.js, the use of 'fs' on a client component isn't allowed, and generating a Blob on a client component has been problematic.

Generating the file the way you suggest in a server action and writing it out works for me though. I can then just download the generated files on the client side. Thank you very much! I am not sure if this was a next.js issue or a fileSaver one.

**Comment by nicolasiscoding** [comment]
@MemduhG going to close this for the time being, but curious, try generating it in Next, pushing it to the backend and then doing the fs.writefile there. This will give us more of a story

**Comment by nicolasiscoding** [comment]
Generating from the backend and serving to client
