### ISSUE TITLE
Fix spacing issues in example files

### ISSUE THREAD

**Issue by nicolasiscoding** [TurboDocx/html-to-docx#47]
![image](https://github.com/user-attachments/assets/df432bfa-2add-4f0a-856c-f6bfdcf9f235)

```
        <p>
         paragraph <strong>temporary</strong> <em>lorem</em> <u>test tag</u>
        </p>
```

**Comment by shareefalis** [comment]
I had to use a workaround involving spaces in italic inner html 

```       i.innerHTML = ' ' + element.innerHTML + ' ';```

**Comment by shareefalis** [comment]
You can close this, i tested it on my app end. it is working well! 
Thanks!
